defmodule Mixer.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :username, :text
      add :display_name, :text
      add :avatar_url, :text
    end

    create unique_index(:users, [:username], name: "users_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:username], name: "users_unique_username_index")

    alter table(:users) do
      remove :avatar_url
      remove :display_name
      remove :username
    end
  end
end
